#!/bin/bash

set -e

export DB_HOST=${DB_HOST:-database}
export DB_PORT=${DB_PORT:-3306}
export DB_JDBC=${DB_JDBC:-mysql}
export DB_DATABASE=${DB_DATABASE:-mydb}
export DB_USER=${DB_USER:-root}
export DB_PASSWORD${DB_PASSWORD:-mysql}
export DB_SQLDIR=${DB_SQLDIR:-/db/}

# Should we update the database?
if [ -n "${UPDATE_DB}" ]; then
  sleep 30
  flyway migrate -url="jdbc:${DB_JDBC}://${DB_HOST}/${DB_DATABASE}" -user=${DB_USER} -password=${DB_PASSWORD} -locations=filesystem:${DB_SQLDIR}
fi

asadmin start-domain --verbose